import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';

/**
 * The Terms of Service page (public route `/terms`, linked from the app-wide
 * footer). Static legal copy hand-authored as semantic HTML — numbered sections
 * are `<h2>`, lettered subsections `<h3>` — rather than rendered from Markdown,
 * since this is the only long-form static page in the app and a Markdown
 * dependency wouldn't pay for itself. Shares typography with the other legal
 * pages via `legal-page.scss`.
 */
@Component({
  selector: 'app-terms-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink],
  template: `
    <main class="legal-page legal-doc">
      <a class="legal-back" routerLink="/">← Back to Invoice-Gen</a>
      <h1>Terms of Service — Invoice-Gen</h1>
      <p class="legal-meta"><strong>Last Updated:</strong> 09/10/2026</p>

      <p>
        Please read these Terms of Service ("Terms") carefully before using
        Invoice-Gen.
      </p>
      <p>
        By accessing or using the Service, you ("Customer," "you") agree to be
        bound by these Terms. If you are agreeing to these Terms on behalf of a
        company or other legal entity, you represent that you have the authority
        to bind that entity, in which case "you" refers to that entity as well.
      </p>
      <p>
        These Terms are an agreement between
        <strong>Dmitrii Ivanovich Degtev</strong>, an Individual Entrepreneur
        registered under the laws of the Republic of Armenia (Tax Identification
        Number 20363621; registered address: 81/1 Manushyan St., 0012, Arabkir,
        Yerevan, Armenia), operating the Invoice-Gen service ("Company," "we,"
        "us," "our"), and the customer agreeing to these Terms ("Customer,"
        "you").
      </p>

      <h2>1. The Service</h2>
      <p>
        Invoice-Gen is a web-based software service that lets Customer create,
        manage, download, and send billing documents — invoices, receipts, and
        other supported document types (the "Service").
      </p>

      <h2>2. Use of the Service</h2>

      <h3>a. Customer Data</h3>
      <p>
        All content, information, logos, and other data that Customer submits to
        or generates through the Service ("Customer Data") remains the property
        of Customer. Customer grants the Company the limited right to store,
        process, and display Customer Data solely as necessary to provide the
        Service.
      </p>

      <h3>b. Contractor Access and Usage</h3>
      <p>
        Customer may allow its own employees or contractors to access the
        Service on Customer's behalf, provided such access is solely for
        Customer's benefit and in compliance with these Terms. Customer remains
        responsible for its employees' and contractors' compliance with these
        Terms.
      </p>

      <h3>c. Customer Responsibilities</h3>
      <p>
        Customer must (i) keep account credentials confidential and secure; (ii)
        is solely responsible for all activity occurring under Customer's
        account; (iii) must promptly notify the Company of any suspected
        unauthorized access to Customer's account; and (iv) must use the Service
        only in compliance with these Terms and applicable law.
      </p>

      <h2>3. Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED "AS IS." TO THE MAXIMUM EXTENT PERMITTED BY LAW,
        THE COMPANY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
        IMPLIED, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        WHILE THE COMPANY TAKES REASONABLE MEASURES TO SECURE THE SERVICE, THE
        COMPANY DOES NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED,
        ERROR-FREE, OR SECURE, AND DOES NOT WARRANT THE ACCURACY OF ANY DOCUMENT,
        CALCULATION, OR TAX FIGURE GENERATED BY THE SERVICE.
      </p>

      <h2>4. Proprietary Rights</h2>

      <h3>a. Reservation of Rights</h3>
      <p>
        The software, user interface, design, and underlying technology of the
        Service are the proprietary property of the Company. Except for the
        limited right to use the Service as permitted by these Terms, the Company
        reserves all rights, title, and interest in and to the Service, including
        all associated intellectual property rights.
      </p>

      <h3>b. Restrictions</h3>
      <p>
        Customer may not: (i) sell, resell, rent, lease, or otherwise provide the
        Service to a third party; (ii) use the Service to store or transmit
        unlawful, infringing, defamatory, or otherwise objectionable material, or
        material that violates a third party's rights, including sending
        unsolicited bulk communications; (iii) interfere with or disrupt the
        integrity or performance of the Service; (iv) attempt to gain
        unauthorized access to the Service or its related systems; (v) reverse
        engineer or decompile the Service; or (vi) access the Service to build a
        competing product, or copy its features, functions, or design for
        competitive purposes.
      </p>

      <h3>c. Aggregate Data</h3>
      <p>
        The Company may use Customer Data in de-identified, aggregated form (i.e.,
        not identifying Customer or any individual) to improve, analyze, and
        support the Service.
      </p>

      <h2>5. Fees</h2>
      <p>
        The Service is currently provided free of charge. If the Company
        introduces paid plans or features, these Terms will be updated to describe
        the applicable fees before any charges apply.
      </p>

      <h2>6. Term and Termination</h2>

      <h3>a. Term</h3>
      <p>
        These Terms remain in effect for as long as Customer maintains an account
        with the Service.
      </p>

      <h3>b. Termination</h3>
      <p>
        Either party may stop using / terminate this agreement at any time. The
        Company may suspend or terminate Customer's access to the Service if
        Customer materially breaches these Terms and does not cure the breach
        within a reasonable time after notice.
      </p>

      <h3>c. Data After Termination</h3>
      <p>
        If Customer deletes their account, Customer Data is deleted immediately
        upon that request. This action is permanent and cannot be undone.
      </p>

      <h3>d. Suspension for Unlawful Use</h3>
      <p>
        The Company may suspend the Service or remove Customer Data if it
        reasonably believes, in good faith, that Customer has used the Service in
        violation of applicable law. Where practicable, the Company will attempt
        to notify Customer in advance.
      </p>

      <h2>7. Limitation of Liability</h2>

      <h3>a. Exclusion of Indirect Damages</h3>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE COMPANY IS NOT LIABLE FOR ANY
        INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR
        RELATED TO THESE TERMS OR THE SERVICE, INCLUDING WITHOUT LIMITATION LOST
        PROFITS OR LOST DATA, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE
        POSSIBILITY OF SUCH DAMAGES.
      </p>

      <h3>b. Liability Cap</h3>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE COMPANY'S TOTAL LIABILITY
        ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE WILL NOT EXCEED
        THE AMOUNT, IF ANY, CUSTOMER PAID THE COMPANY IN THE SIX (6) MONTHS
        PRECEDING THE EVENT GIVING RISE TO THE LIABILITY.
      </p>

      <h2>8. Indemnification</h2>
      <p>
        Customer agrees to defend, indemnify, and hold the Company harmless from
        any claim, damage, loss, or expense (including reasonable attorneys' fees)
        arising from a third party's claim relating to Customer's acts, omissions,
        or Customer Data.
      </p>

      <h2>9. Governing Law and Forum</h2>
      <p>
        These Terms are governed by the laws of the Republic of Armenia, without
        regard to its conflict-of-laws principles. Any dispute arising out of or
        relating to these Terms or the Service will be brought exclusively in the
        competent courts of Yerevan, Armenia, and Customer consents to the
        personal jurisdiction of such courts. Nothing in these Terms prevents
        either party from seeking injunctive relief in a court of competent
        jurisdiction.
      </p>

      <h2>10. General</h2>

      <h3>a. Changes to These Terms</h3>
      <p>
        The Company may update these Terms from time to time. Material changes
        will be indicated by updating the "Last Updated" date above, and continued
        use of the Service after such changes constitutes acceptance of the
        updated Terms.
      </p>

      <h3>b. Entire Agreement</h3>
      <p>
        These Terms, together with the Company's Privacy Policy, constitute the
        entire agreement between Customer and the Company regarding the Service,
        and supersede any prior agreements on the subject.
      </p>

      <h3>c. Severability</h3>
      <p>
        If any provision of these Terms is found unenforceable, the remaining
        provisions will remain in full force and effect.
      </p>

      <h3>d. Contact</h3>
      <p>
        Questions about these Terms can be sent to
        <a href="mailto:axenpartnership@gmail.com">axenpartnership&#64;gmail.com</a>.
      </p>

      <h2>11. Other Terms</h2>

      <h3>a. No Assignment</h3>
      <p>
        Neither party may assign or transfer these Terms to a third party without
        the other party's consent, except that the Company may assign these Terms
        as part of a merger, acquisition, or sale of substantially all of its
        assets, without Customer's consent.
      </p>

      <h3>b. Independent Contractors</h3>
      <p>
        The parties are independent contractors with respect to each other.
        Nothing in these Terms creates a partnership, joint venture, agency, or
        employment relationship.
      </p>

      <h3>c. Force Majeure</h3>
      <p>
        Except for payment obligations, neither party is liable for any failure or
        delay in performance caused by events beyond its reasonable control.
      </p>

      <h3>d. Survival</h3>
      <p>
        Provisions of these Terms that by their nature should survive termination
        — including, without limitation, Proprietary Rights, Limitation of
        Liability, Indemnification, and Governing Law and Forum — will survive
        termination of these Terms.
      </p>

      <h3>e. Feedback</h3>
      <p>
        If Customer submits ideas, suggestions, or feedback about the Service,
        Customer agrees such feedback is not confidential, and grants the Company
        an irrevocable, royalty-free, perpetual license to use it for any business
        purpose.
      </p>
    </main>
  `,
  styleUrl: './legal-page.scss',
})
export class TermsPage {}
