/* eslint-disable */
/* Hand-authored, NOT generated by ng-openapi-gen.
 *
 * `POST /api/search` isn't in the backend's `openapi.yaml` yet, so it has no
 * generated function. This mirrors the shape ng-openapi-gen emits (a thin
 * `RequestBuilder` call plus a `PATH`) so it plugs into `Api.invoke` exactly
 * like a generated one, and the auth interceptor attaches the bearer token
 * automatically since `/api/search` isn't a public path. Once the endpoint is
 * added to the spec, delete this file and regenerate. See docs/api-client.md. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchRequest } from '../../models/search-request';
import { SearchResponse } from '../../models/search-response';

export interface SearchDocuments$Params {
      body: SearchRequest
}

export function searchDocuments(http: HttpClient, rootUrl: string, params: SearchDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchResponse>> {
  const rb = new RequestBuilder(rootUrl, searchDocuments.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchResponse>;
    })
  );
}

searchDocuments.PATH = '/api/search';
