/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TokenPair } from '../models/token-pair';
import { User } from '../models/user';
export type AuthResponse = TokenPair & {
'user'?: User;
};

