/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from '../models/document-type';
import { LineItem } from '../models/line-item';
import { MonetaryAmount } from '../models/monetary-amount';

/**
 * The submitted form. `from` may be omitted if the user has set a default business profile via `PATCH /auth/me`.
 */
export interface CreateDocumentRequest {

  /**
   * Money already paid (most types) or already refunded (`credit_note`) against this document. See `x-settlement-policy` for the full, type-dependent explanation.
   */
  amount_settled?: MonetaryAmount;
  currency?: string;

  /**
   * Optional reference to a saved Customer (`POST /customers`). Purely for convenience (auto-filling `to`) and later filtering (`GET /documents?customer_id=...`) — a document never requires one, `to` can always just be typed as free text. Referencing a customer that doesn't exist or was deleted returns a 422.
   */
  customer_id?: string | null;
  date: string;

  /**
   * e.g. 5 for 5%. Applied BEFORE tax — see x-rounding-policy (discount_tax_ordering) for the exact ordering and a worked example.
   */
  discount_percent?: number;
  due_date?: string | null;

  /**
   * Billing organization's name/address. Falls back to the user's saved business profile if omitted.
   */
  from?: string;
  items: Array<LineItem>;
  notes?: string;

  /**
   * Optional free-text document number/reference, e.g. "INV-0042" or a custom scheme like "NBL-1321-DW". Stored exactly as submitted — the API never auto-generates it, validates it for uniqueness, or otherwise mutates it; if omitted it is simply left blank on the document. The FRONTEND may pre-fill this field as a convenience (not an API concern) by taking the user's most recent document of the same type — `GET /documents?type=...&per_page=1` is ordered newest-first for exactly this purpose — and incrementing a trailing numeric run with a conservative regex such as `^(.*?)(\d+)$` (so "INV-0042" -> "INV-0043"). If the previous number doesn't match that pattern (e.g. "NBL-1321-DW", where the digits aren't at the end), there is no reliable way to guess "the next one" — the frontend should leave the field blank rather than insert a wrong guess.
   */
  number?: string | null;

  /**
   * Optional free-text reference to another document this one relates to — most commonly the invoice a `credit_note` is crediting, e.g. "INV-0042". Same free-text philosophy as `number`: never validated against, or linked by ID to, an actual document in this system — it may reference an invoice issued outside this system entirely, or from before this system existed. If omitted, left blank on the document. Meaningful mainly for `credit_note`; harmless but typically unused on other types.
   */
  related_document_number?: string | null;
  shipping_amount?: MonetaryAmount;

  /**
   * e.g. 8.5 for 8.5%. See x-rounding-policy for how this is applied (per line item, not on the subtotal).
   */
  tax_percent?: number;
  terms?: string;

  /**
   * Customer's name/address (multiline). If `customer_id` is also given and `to` is omitted, `to` is auto-filled from that customer's current name/address at creation time. An explicit `to` always wins over the customer's saved info. Once created, this text is frozen on the document — see `x-customer-policy`.
   */
  to: string;
  type: DocumentType;
}
