/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCustomerRequest {

  /**
   * Multiline.
   */
  address?: string;
  email?: string;
  name: string;
  notes?: string;
  phone?: string;
}
