/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Customer } from '../models/customer';
export interface CustomerList {
  data?: Array<Customer>;
  page?: number;
  per_page?: number;
  total?: number;
}
