/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from './document-type';

/**
 * Each possible value of `DocumentType`
 */
export const DOCUMENT_TYPE: DocumentType[] = [
  'invoice',
  'receipt',
  'credit_note',
  'quote',
  'estimate',
  'proforma_invoice',
  'purchase_order',
  'statement',
  'timesheet',
  'work_order',
  'packing_slip',
  'sales_order'
];