/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from '../models/document-type';

/**
 * Metadata for one document type. Originally introduced for the main page's "what to generate" picker, but `name` in particular is now the canonical source of a type's display name — see its own description.
 */
export interface DocumentTypeInfo {
  description?: string;

  /**
   * Icon identifier for the frontend.
   */
  icon?: string;
  id?: DocumentType;

  /**
   * The canonical human-readable label for this document type. This is the single source of truth for how a type is displayed to a user, and MUST be reused anywhere a type is shown — the main page picker, PDF titles, and any future surface (email subject lines, etc.) — rather than re-derived from the raw `DocumentType` enum value. (The enum's `credit_note`, or a naive `.ToString()` on a `CreditNote` C# enum member, is not fit for display — this field is.)
   */
  name?: string;
}
