/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from '../models/document-type';
import { MonetaryAmount } from '../models/monetary-amount';
export interface Document {

  /**
   * Money paid (most types) or refunded (credit_note) so far. See x-settlement-policy.
   */
  amount_settled?: MonetaryAmount;

  /**
   * total minus amount_settled. Owed by the customer (most types), or owed back to them (credit_note). See x-settlement-policy.
   */
  balance_remaining?: MonetaryAmount;
  created_at?: string;
  currency?: string;

  /**
   * Reference to the Customer this was created from, if any. Kept even after that customer is soft-deleted (see x-customer-policy) — does not imply `to` reflects the customer's current info.
   */
  customer_id?: string | null;
  from?: string;
  id?: string;

  /**
   * Short human-readable reason the most recent send failed. Only present when last_send_status is "failed"; null otherwise.
   */
  last_send_error?: string | null;

  /**
   * Outcome of the MOST RECENT send attempt. Null if never sent. See x-email-delivery-policy.status_and_failure_visibility for how the frontend should use this to alert the user on failure.
   */
  last_send_status?: ('queued' | 'sent' | 'failed') | null;

  /**
   * When this document was last SUCCESSFULLY emailed via POST /documents/{id}/send. Null if it's never been sent. Only updates on success — see x-email-delivery-policy.
   */
  last_sent_at?: string | null;

  /**
   * Exactly what the user submitted (or null if left blank) — see CreateDocumentRequest.number for the full policy. Never generated or altered by the API.
   */
  number?: string | null;

  /**
   * Same as GET /documents/{id}/pdf — provided here for convenience.
   */
  pdf_url?: string;

  /**
   * Exactly what the user submitted (or null if left blank) — see CreateDocumentRequest.related_document_number for the full policy. Never generated, validated, or altered by the API.
   */
  related_document_number?: string | null;

  /**
   * How many times a send has been attempted (including retries after a failure) — not just successful sends. See x-email-delivery-policy.
   */
  send_count?: number;

  /**
   * Phase 1 only distinguishes 'saved but not rendered yet' vs 'PDF ready'. Statuses like sent/paid belong to a later phase (see x-future-phases).
   */
  status?: 'draft' | 'generated';
  subtotal?: MonetaryAmount;
  to?: string;
  total?: MonetaryAmount;
  type?: DocumentType;
  updated_at?: string;
}
