/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Document } from '../models/document';
export interface DocumentList {
  data?: Array<Document>;
  page?: number;
  per_page?: number;
  total?: number;
}
