/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GoogleSignInRequest {

  /**
   * The ID token (a JWT) issued by Google Sign-In on the client. It is verified server-side against Google's public keys; the app never trusts a client-decoded payload. See `x-google-auth-policy`.
   */
  id_token: string;
}
