/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from '../models/document-type';
import { LineItem } from '../models/line-item';
import { MonetaryAmount } from '../models/monetary-amount';

/**
 * The body for `POST /documents/guest` — the unauthenticated try-before- you-sign-up flow. Deliberately the SAME shape as `CreateDocumentRequest` with two differences: (1) `customer_id` is absent entirely — a guest has no saved customers, so `to` is always plain free text; and (2) `from` is REQUIRED rather than optional, because there is no signed-in business profile to fall back on. Everything else — the line items, the tax/discount/shipping inputs, `number`, dates, notes/terms — is identical, and the totals are computed by the exact same code path (`x-rounding-policy`). There is no `include_logo`: a guest has no profile logo to stamp. See `x-guest-document-policy`.
 */
export interface GuestCreateDocumentRequest {

  /**
   * Same meaning/rules as CreateDocumentRequest.amount_settled — see x-settlement-policy.
   */
  amount_settled?: MonetaryAmount;
  currency?: string;
  date: string;

  /**
   * Applied BEFORE tax — see x-rounding-policy (discount_tax_ordering).
   */
  discount_percent?: number;
  due_date?: string | null;

  /**
   * Billing organization's name/address. REQUIRED here (no saved profile to fall back on, unlike CreateDocumentRequest).
   */
  from: string;
  items: Array<LineItem>;
  notes?: string;

  /**
   * Optional free-text document number, same policy as CreateDocumentRequest.number — never generated, validated, or mutated by the API.
   */
  number?: string | null;

  /**
   * Optional free-text reference, same policy as CreateDocumentRequest.related_document_number.
   */
  related_document_number?: string | null;
  shipping_amount?: MonetaryAmount;

  /**
   * See x-rounding-policy — applied per line item, identically to CreateDocumentRequest.
   */
  tax_percent?: number;
  terms?: string;

  /**
   * Customer's name/address (multiline free text). Always required — a guest has no customer_id to auto-fill it from.
   */
  to: string;
  type: DocumentType;
}
