/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MonetaryAmount } from '../models/monetary-amount';
export interface LineItem {
  description?: string;
  name: string;
  quantity: number;
  reference?: string;
  unit_cost: MonetaryAmount;
}
