/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * A decimal monetary amount (never a percentage). JSON has no native decimal type, so on the wire this is a plain JSON number — but it MUST be deserialized into a fixed-point decimal type server-side (.NET: `decimal`, never `double`/`float`) to avoid floating-point rounding errors. See the root-level `x-rounding-policy` for the full rationale and a worked example.
 */
export type MonetaryAmount = number;

