/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MonetaryAmount } from '../models/monetary-amount';

/**
 * Body for `POST /documents/{documentId}/settlements`. See `x-settlement-policy.recording_settlements`.
 */
export interface RecordSettlementRequest {

  /**
   * Signed delta added to the document's current `amount_settled` — NOT the new absolute value. Positive records money received (or, for `credit_note`, refunded); negative corrects a previous over-entry. Rejected with `422` (field `amount`) if it would push `amount_settled` below zero or above `total`.
   */
  amount: MonetaryAmount;
}
