/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MonetaryAmount } from '../models/monetary-amount';

/**
 * A single signed change to the document's `amount_settled`. Positive records a payment/refund received; negative corrects a previous mistaken entry (no separate payment history is kept — this is the one way to fix a mistake). The resulting `amount_settled + amount` must land within `[0, total]`. See `x-settlement-policy` for what "settled" means per `type`.
 */
export interface RecordSettlementRequest {

  /**
   * Signed delta applied to `amount_settled` (may be negative). The resulting settled amount must stay within `[0, total]`, else `422` on the `amount` field.
   */
  amount: MonetaryAmount;
}
