/* eslint-disable */
/* Hand-authored, NOT generated by ng-openapi-gen.
 *
 * `POST /api/search` isn't in the backend's `openapi.yaml` yet, so it has no
 * generated counterpart. Keep this shape in step with the backend contract, and
 * once the endpoint lands in the spec, delete this file and let
 * `ng-openapi-gen` own it (see docs/api-client.md). */

/**
 * Body for `POST /api/search`: a natural-language `query` plus optional
 * structured filters that narrow the result set. All filters are optional — an
 * omitted filter isn't applied.
 */
export interface SearchRequest {

  /** Natural-language search text (e.g. "unpaid invoices for Acme last month"). */
  query: string;

  /**
   * Restrict to documents in this status. Mirrors `Document.status`
   * (see the generated `Document` model) — Phase 1 only distinguishes
   * 'draft' vs 'generated'.
   */
  status?: 'draft' | 'generated';

  /** Lower bound (inclusive) on a document's `total`. */
  min_amount?: number;

  /** Upper bound (inclusive) on a document's `total`. */
  max_amount?: number;

  /** Only match documents dated on/after this day (ISO `YYYY-MM-DD`). */
  date_from?: string;

  /** Only match documents dated on/before this day (ISO `YYYY-MM-DD`). */
  date_to?: string;
}
