/* eslint-disable */
/* Hand-authored, NOT generated by ng-openapi-gen — see search-request.ts. */

import { SearchResult } from '../models/search-result';

/** Body returned by `POST /api/search`: the ranked list of matching documents. */
export interface SearchResponse {

  /** Matches, ordered by relevance (best first). Empty when nothing matched. */
  results?: Array<SearchResult>;
}
