/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Both fields optional — an empty body is valid whenever the document has a `customer_id` with a saved email. See `x-email-delivery-policy.recipient_resolution`.
 */
export interface SendDocumentRequest {

  /**
   * Optional free-text note included in the email body. The subject line is always auto-generated and not customizable — see `x-email-delivery-policy.subject_and_message`.
   */
  message?: string;

  /**
   * Overrides the linked Customer's saved email, if any. Required when the document has no `customer_id`, or that customer has no `email` on file.
   */
  to_email?: string;
}
