/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TokenPair {
  access_token?: string;

  /**
   * Access token lifetime in seconds.
   */
  expires_in?: number;
  refresh_token?: string;
  token_type?: string;
}
