/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * All fields optional — send only what's changing.
 */
export interface UpdateCustomerRequest {
  address?: string;
  email?: string;
  name?: string;
  notes?: string;
  phone?: string;
}
