/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserRequest {

  /**
   * Multiline, used to pre-fill the 'from' field.
   */
  business_address?: string;
  business_name?: string;
  default_currency?: string;
  logo_url?: string;
}
