/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ValidationErrorResponse {
  error: {
'code': string;
'message': string;
'fields': Array<{
'field'?: string;
'message'?: string;
}>;
};
}
